{
 "title": "Python Process",
 "description": "Metrics related to the python process and resource usage like CPU, RAM, Garbage Collection, file descriptors and others that are automaticly exposed by async-worker applications.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])) by (instance)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "python_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Max file descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "graph",
   "description": "Number of objects collected during gc.\t",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "python_gc_collections_total{instance=~\"$instance\"}",
     "legendFormat": "collected - gen {{ generation }}"
    }
   ]
  }
 ]
}