global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'observability-stack'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['spring-app:8080']

  - job_name: 'python app'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['python-app:8082']